### ISSUE TITLE
CalendarInput returning a string when passed a number

### ISSUE THREAD

**Issue by adamiprinciples** [Rocketmakers/armstrong-edge#58]
## Bug report
When you pass a number to a `CalendarInput` it returns a date string rather than a number, even though the formatters (toData/fromData) claim it's a number

### Expected Behaviour
Passing a number in to the binder should return a number in the form state

### Actual Behaviour
A date string is returned

### Steps to Reproduce
```
 const { formProp, formState } = Form.use<ICreateStagingJobApiParams>({
    vendorId: '',
    companyId: '',
    customerId: '',
    juniperProductId: '',
    oldestReleaseDate: 0,
    maxFirmware: 0,
  });
 <CalendarInput displayMode="inputs" bind={formProp('oldestReleaseDate').bind()}/>
```
Log form state, `oldestReleaseDate` will be a date string

**Comment by patrickbenjamin1** [comment]
I remember seeing some discussion in Slack on this a while ago, and I vaguely remember seeing it fixed - am I misremembering or can this issue be closed off?

**Comment by patrickbenjamin1** [comment]
apparently it's not fixed - one we should discuss with @jlews probably as this is potentially gonna be quite deep in form gubbins

One important thing here is that we're not gonna be able to get it to just know what to use based on the type in case it doesn't already have a value, so we'll have to specify it - could be something like passing the value `"unix"` into `displayFormatString`? Could also use a generic to make it so that if that's there it always binds a number

**Comment by jlews** [comment]
Resolved by PR: https://github.com/Rocketmakers/armstrong-edge/pull/87
